
spring:
  application:
    name: ex09

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3303/lsj
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: true

my:
  value: "welcome to my value"